# Generated by Django 3.2 on 2021-11-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_auto_20211128_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='title',
        ),
    ]
